/**
 * Report generation — CSV and HTML output from query results.
 */

export interface ColumnInfo {
  name: string;
  type: string;
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function escapeCsvField(value: unknown): string {
  const str = value === null || value === undefined ? '' : String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function generateCsv(columns: ColumnInfo[], rows: unknown[][]): string {
  const header = columns.map((c) => escapeCsvField(c.name)).join(',');
  const body = rows.map((row) => row.map(escapeCsvField).join(',')).join('\n');
  return `${header}\n${body}`;
}

export function generateHtmlReport(
  reportName: string,
  columns: ColumnInfo[],
  rows: unknown[][],
  generatedAt: string,
): string {
  const headerCells = columns.map((c) => `<th style="border:1px solid #ddd;padding:8px;background:#f4f4f4;text-align:left;">${escapeHtml(c.name)}</th>`).join('');
  const bodyRows = rows
    .map(
      (row) =>
        `<tr>${row.map((cell) => `<td style="border:1px solid #ddd;padding:6px;">${escapeHtml(String(cell ?? ''))}</td>`).join('')}</tr>`,
    )
    .join('\n');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>${escapeHtml(reportName)}</title></head>
<body style="font-family:Arial,sans-serif;margin:40px;">
  <h1 style="color:#1a1a2e;">${escapeHtml(reportName)}</h1>
  <p style="color:#666;">Generated ${escapeHtml(generatedAt)} &mdash; ${rows.length} row${rows.length !== 1 ? 's' : ''}</p>
  <table style="border-collapse:collapse;width:100%;margin-top:20px;">
    <thead><tr>${headerCells}</tr></thead>
    <tbody>${bodyRows}</tbody>
  </table>
  <p style="color:#999;margin-top:40px;font-size:12px;">Report generated by Apura</p>
</body>
</html>`;
}

export async function executeQuery(
  wsGateway: Fetcher,
  internalSecret: string,
  orgId: string,
  sql: string,
): Promise<{ columns: ColumnInfo[]; rows: unknown[][] }> {
  const queryId = crypto.randomUUID();
  const resp = await wsGateway.fetch('https://ws-gateway/query/execute', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Internal-Secret': internalSecret,
    },
    body: JSON.stringify({ orgId, queryId, sql }),
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Query execution failed (${resp.status}): ${text}`);
  }

  return resp.json<{ columns: ColumnInfo[]; rows: unknown[][] }>();
}
