name = "apura-cron-worker"
account_id = "616231e4ffa88bb203ec4cbedeab4a8e"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "apura-main"
database_id = "48a7c67d-223e-4ee1-8c87-9a9b3231def0"

[[queues.producers]]
binding = "REPORT_QUEUE"
queue = "report-generation"

# Run every minute to check for due schedules
[triggers]
crons = ["* * * * *"]
