name = "apura-ws"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "ws.apura.xyz/*", zone_name = "apura.xyz" }
]

[[d1_databases]]
binding = "DB"
database_name = "apura-main"
database_id = "48a7c67d-223e-4ee1-8c87-9a9b3231def0"

[[kv_namespaces]]
binding = "CACHE"
id = "290e5fb7d86847b6823b79be9b6d2cb4"

[durable_objects]
bindings = [
  { name = "CONNECTOR", class_name = "ConnectorSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["ConnectorSession"]
