/**
 * Report Worker — PDF/CSV generation via Queues consumer.
 *
 * Consumes messages from the `report-generation` queue, executes the
 * underlying query via ws-gateway, generates CSV or HTML/PDF output,
 * stores the file in R2, and publishes to the `email-outbound` queue.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Env {
  DB: D1Database;
  REPORTS_BUCKET: R2Bucket;
  EMAIL_QUEUE: Queue;
  WS_GATEWAY: Fetcher;
  INTERNAL_SECRET: string;
}

interface ReportMessage {
  scheduleId: string;
  scheduleRunId: string;
  reportId: string;
  orgId: string;
  userId: string;
  outputFormat: 'pdf' | 'csv';
  recipients: string[];
  reportName: string;
}

interface ColumnInfo {
  name: string;
  type: string;
}

// ---------------------------------------------------------------------------
// CSV generation
// ---------------------------------------------------------------------------

function escapeCsvField(value: unknown): string {
  const str = value === null || value === undefined ? '' : String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function generateCsv(columns: ColumnInfo[], rows: unknown[][]): string {
  const header = columns.map((c) => escapeCsvField(c.name)).join(',');
  const body = rows.map((row) => row.map(escapeCsvField).join(',')).join('\n');
  return `${header}\n${body}`;
}

// ---------------------------------------------------------------------------
// HTML report generation (used as PDF substitute in Workers)
// ---------------------------------------------------------------------------

function generateHtmlReport(
  reportName: string,
  columns: ColumnInfo[],
  rows: unknown[][],
  generatedAt: string,
): string {
  const headerCells = columns.map((c) => `<th style="border:1px solid #ddd;padding:8px;background:#f4f4f4;text-align:left;">${escapeHtml(c.name)}</th>`).join('');
  const bodyRows = rows
    .map(
      (row) =>
        `<tr>${row.map((cell) => `<td style="border:1px solid #ddd;padding:6px;">${escapeHtml(String(cell ?? ''))}</td>`).join('')}</tr>`,
    )
    .join('\n');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>${escapeHtml(reportName)}</title></head>
<body style="font-family:Arial,sans-serif;margin:40px;">
  <h1 style="color:#1a1a2e;">${escapeHtml(reportName)}</h1>
  <p style="color:#666;">Generated ${escapeHtml(generatedAt)} &mdash; ${rows.length} row${rows.length !== 1 ? 's' : ''}</p>
  <table style="border-collapse:collapse;width:100%;margin-top:20px;">
    <thead><tr>${headerCells}</tr></thead>
    <tbody>${bodyRows}</tbody>
  </table>
  <p style="color:#999;margin-top:40px;font-size:12px;">Report generated by Apura</p>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ---------------------------------------------------------------------------
// Query execution helper
// ---------------------------------------------------------------------------

async function executeQuery(
  env: Env,
  orgId: string,
  sql: string,
): Promise<{ columns: ColumnInfo[]; rows: unknown[][] }> {
  const queryId = crypto.randomUUID();
  const resp = await env.WS_GATEWAY.fetch('https://ws-gateway/query/execute', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Internal-Secret': env.INTERNAL_SECRET,
    },
    body: JSON.stringify({ orgId, queryId, sql }),
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Query execution failed (${resp.status}): ${text}`);
  }

  const result = await resp.json<{ columns: ColumnInfo[]; rows: unknown[][] }>();
  return result;
}

// ---------------------------------------------------------------------------
// Worker export
// ---------------------------------------------------------------------------

export default {
  // Queue consumer
  async queue(batch: MessageBatch<ReportMessage>, env: Env): Promise<void> {
    for (const msg of batch.messages) {
      try {
        await processReport(msg.body, env);
        msg.ack();
      } catch (err) {
        console.error(`Failed to process report ${msg.body.reportId}:`, err);

        // Update schedule_runs with error
        await env.DB.prepare(
          `UPDATE schedule_runs SET status = 'failed', error_message = ?, completed_at = datetime('now') WHERE id = ?`,
        )
          .bind(err instanceof Error ? err.message : 'Unknown error', msg.body.scheduleRunId)
          .run();

        msg.retry();
      }
    }
  },

  // Health check fetch handler
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === '/health') {
      return Response.json({ status: 'ok', service: 'report-worker', timestamp: new Date().toISOString() });
    }
    return Response.json({ error: 'Not found' }, { status: 404 });
  },
};

// ---------------------------------------------------------------------------
// Core report processing
// ---------------------------------------------------------------------------

async function processReport(message: ReportMessage, env: Env): Promise<void> {
  const { scheduleRunId, reportId, orgId, outputFormat, recipients, reportName } = message;

  // Mark run as in-progress
  await env.DB.prepare(
    `UPDATE schedule_runs SET status = 'running', started_at = datetime('now') WHERE id = ?`,
  )
    .bind(scheduleRunId)
    .run();

  // Fetch the report's underlying query SQL
  const report = await env.DB.prepare(
    `SELECT r.name, q.generated_sql FROM reports r JOIN saved_queries q ON r.query_id = q.id WHERE r.id = ? AND r.org_id = ?`,
  )
    .bind(reportId, orgId)
    .first<{ name: string; generated_sql: string }>();

  if (!report) {
    throw new Error(`Report ${reportId} not found for org ${orgId}`);
  }

  // Execute the query via ws-gateway
  const { columns, rows } = await executeQuery(env, orgId, report.generated_sql);

  // Generate output
  const generatedAt = new Date().toISOString();
  let fileContent: string;
  let contentType: string;
  let fileExtension: string;

  if (outputFormat === 'csv') {
    fileContent = generateCsv(columns, rows);
    contentType = 'text/csv';
    fileExtension = 'csv';
  } else {
    // PDF format — generate HTML report (Workers cannot run headless browsers)
    fileContent = generateHtmlReport(reportName, columns, rows, generatedAt);
    contentType = 'text/html';
    fileExtension = 'html';
  }

  // Store in R2
  const objectKey = `reports/${orgId}/${reportId}/${scheduleRunId}.${fileExtension}`;
  await env.REPORTS_BUCKET.put(objectKey, fileContent, {
    httpMetadata: { contentType },
    customMetadata: {
      reportId,
      orgId,
      generatedAt,
      rowCount: String(rows.length),
    },
  });

  // Update schedule run with output URL
  const outputUrl = objectKey;
  await env.DB.prepare(
    `UPDATE schedule_runs SET status = 'completed', output_url = ?, completed_at = datetime('now') WHERE id = ?`,
  )
    .bind(outputUrl, scheduleRunId)
    .run();

  // Publish to email queue
  if (recipients.length > 0) {
    await env.EMAIL_QUEUE.send({
      type: 'scheduled_report',
      to: recipients,
      subject: `Scheduled Report: ${reportName}`,
      reportName,
      reportObjectKey: objectKey,
      generatedAt,
      rowCount: rows.length,
      format: fileExtension,
    });
  }
}
