name = "apura-report-worker"
account_id = "616231e4ffa88bb203ec4cbedeab4a8e"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "REPORTS_BUCKET"
bucket_name = "apura-reports"

[[d1_databases]]
binding = "DB"
database_name = "apura-main"
database_id = "48a7c67d-223e-4ee1-8c87-9a9b3231def0"

[[queues.consumers]]
queue = "report-generation"
max_batch_size = 5
max_batch_timeout = 30

[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "email-outbound"

[[services]]
binding = "WS_GATEWAY"
service = "apura-ws"

[vars]
INTERNAL_SECRET = "apura-internal-2026-change-me"
